"""update models

Revision ID: 60023c8b3617
Revises: 
Create Date: 2024-11-22 11:05:36.909576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60023c8b3617'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=32), nullable=False))

    # ### end Alembic commands ###
