name: ie-bank-backend

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  BACKEND_WEBAPP_DEV: devious-be-dev
  BACKEND_WEBAPP_UAT: devious-be-uat
  ACR_NAME: deviousacrdev
  IMAGE_NAME: backend

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV: ghci

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8 pytest
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        python -m pytest --cov=iebank_api -v
    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v4
      with:
        name: python-app
        path: |
          .

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: python-app
        path: .
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Get ACR credentials from Dev Key Vault'
      uses: azure/get-keyvault-secrets@v1
      with:
        keyvault: "devious-kv25-dev"
        secrets: 'registry-username, registry-password'
      id: devKeyvaultSecrets
    - name: 'Build and push image for Dev'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ steps.devKeyvaultSecrets.outputs.registry-username }}
        password: ${{ steps.devKeyvaultSecrets.outputs.registry-password }}
    - name: Build and push container image for Dev
      run: |
        docker build . -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}-dev
        docker tag ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}-dev ${{ env.ACR_NAME }}.azurecr.io/backend-dev:${{ github.sha }}
        docker push ${{ env.ACR_NAME }}.azurecr.io/backend-dev:${{ github.sha }}
        docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}-dev
    - name: 'Deploy to Azure Web App Development'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.BACKEND_WEBAPP_DEV }}
        images: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}-dev:latest
        startup-command: flask run --host=0.0.0.0 --port=8000

  deploy-uat:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'UAT'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: python-app
        path: .
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Get ACR credentials from UAT Key Vault'
      uses: azure/get-keyvault-secrets@v1
      with:
        keyvault: "devious-kv21-uat"
        secrets: 'registry-username, registry-password'
      id: uatKeyvaultSecrets
    - name: 'Build and push image for UAT'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ steps.uatKeyvaultSecrets.outputs.registry-username }}
        password: ${{ steps.uatKeyvaultSecrets.outputs.registry-password }}
    - name: Build and push container image for UAT
      run: |
        docker build . -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}-uat
        docker tag ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}-uat ${{ env.ACR_NAME }}.azurecr.io/backend-uat:${{ github.sha }}
        docker push ${{ env.ACR_NAME }}.azurecr.io/backend-uat:${{ github.sha }}
        docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}-uat
    - name: 'Deploy to Azure Web App UAT'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.BACKEND_WEBAPP_UAT }}
        images: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}-uat:latest
        startup-command: flask run --host=0.0.0.0 --port=8000

  run-postman-tests:
    runs-on: ubuntu-latest
    needs: deploy-uat
    environment: 'UAT'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
    - name: Install Newman
      run: npm install -g newman
    - name: Fetch Postman Collection
      run: |
        curl -L -o collection.json "https://api.postman.com/collections/${{ secrets.POSTMAN_COLLECTION_UID }}?apikey=${{ secrets.POSTMAN_API_KEY }}"
    - name: Fetch Postman Environment
      run: |
        curl -L -o environment.json "https://api.postman.com/environments/${{ secrets.POSTMAN_ENVIRONMENT_UID }}?apikey=${{ secrets.POSTMAN_API_KEY }}"
    - name: Run Newman Tests
      run: newman run collection.json -e environment.json